language: r
sudo: false
cache: packages
dist: trusty

r_github_packages:
  - jimhester/covr

r_check_args: "--as-cran --run-dontrun"

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
